FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y bash netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY wait-for-postgres.sh /wait-for-postgres.sh
RUN chmod +x /wait-for-postgres.sh

CMD ["bash", "-c", "/wait-for-postgres.sh $POSTGRES_HOST $POSTGRES_PORT && alembic revision --autogenerate -m 'auto' && alembic upgrade head"]